# 1.7
#
# Makefile for package com.paracel.tt.view
# Copyright (c) 2000 Paracel Inc.
#
BASE_DIR        = ..
CLASS_DIR       = $(BASE_DIR)/com/paracel/tt/view
include $(BASE_DIR)/include.mk

all:	$(CLASS_DIR)/MessagePanel.class \
	$(CLASS_DIR)/TTPrintHeader.class \
	$(CLASS_DIR)/HelpAction.class \
	$(CLASS_DIR)/CustomZoomDialog.class \
	$(CLASS_DIR)/GoToDialog.class \
	$(CLASS_DIR)/Search.class \
	$(CLASS_DIR)/SearchDialog.class \
	$(CLASS_DIR)/PageSetupDialog.class \
	$(CLASS_DIR)/PageSetupManager.class \
	$(CLASS_DIR)/ChromLayout.class \
	$(CLASS_DIR)/ChromDataPainter.class \
	$(CLASS_DIR)/ChromViewPanel.class \
	$(CLASS_DIR)/ChromSnapShot.class \
	$(CLASS_DIR)/TTPrintJob.class \
	$(CLASS_DIR)/PrintPreview.class \
	$(CLASS_DIR)/TTViewFrame.class \
	$(CLASS_DIR)/OpenFileDialog.class \
	$(CLASS_DIR)/Options.class \
	$(CLASS_DIR)/AdvancedOptionsDialog.class \
	$(CLASS_DIR)/BasicOptionsFrame.class

$(CLASS_DIR)/ChromSnapShot.class: TTPrintJob.java
$(CLASS_DIR)/TTViewFrame.class: OpenFileDialog.java


