#
# Makefile for package com.paracel.tt.chrom
# Copyright (c) 2000 Paracel Inc.
#
BASE_DIR        = ..
CLASS_DIR       = $(BASE_DIR)/com/paracel/tt/chrom

include $(BASE_DIR)/include.mk

all:    $(CLASS_DIR)/Trace.class \
	$(CLASS_DIR)/Chromatogram.class \
	$(CLASS_DIR)/AbstractChromatogram.class \
	$(CLASS_DIR)/ABIChromatogram.class \
	$(CLASS_DIR)/SCFChromatogram.class
