# 1.8
#
# Makefile for package com.paracel.tt.util
# Copyright (c) 2000 Paracel Inc.
#
BASE_DIR        = ..
CLASS_DIR       = $(BASE_DIR)/com/paracel/tt/util

include $(BASE_DIR)/include.mk

all:	$(CLASS_DIR)/Constants.class \
	$(CLASS_DIR)/DefaultBrowser.class \
	$(CLASS_DIR)/BaseColorIdentifier.class \
	$(CLASS_DIR)/CommandBuilder.class \
	$(CLASS_DIR)/ErrorLog.class \
	$(CLASS_DIR)/FilesStatus.class \
	$(CLASS_DIR)/Fonts.class \
	$(CLASS_DIR)/Filter.class \
	$(CLASS_DIR)/Filespec.class \
	$(CLASS_DIR)/IUBCode.class \
	$(CLASS_DIR)/LangTools.class \
	$(CLASS_DIR)/SearchConstants.class \
	$(CLASS_DIR)/SNPsTableModel.class
