#
# Makefile for package com.paracel.tt.chrom
# Copyright (c) 2000 Paracel Inc.
#
BASE_DIR        = ..
CLASS_DIR       = $(BASE_DIR)/com/paracel/tt/io

include $(BASE_DIR)/include.mk

all:    $(CLASS_DIR)/ABIFile.class \
	$(CLASS_DIR)/TabFile.class \
	$(CLASS_DIR)/TalFile.class \
	$(CLASS_DIR)/PhdFile.class \
	$(CLASS_DIR)/TipFile.class
