#
# Makefile for package com.paracel.tt.chrom
# Copyright (c) 2000 Paracel Inc.
#
BASE_DIR        = ..
CLASS_DIR       = $(BASE_DIR)/com/paracel/tt/run

include $(BASE_DIR)/include.mk

all:    $(CLASS_DIR)/TTView.class $(CLASS_DIR)/TTrun.class
