#
# Makefile for package com.paracel.tt.event
# Copyright (c) 2000 Paracel Inc.
#
BASE_DIR        = ..
CLASS_DIR       = $(BASE_DIR)/com/paracel/tt/event

include $(BASE_DIR)/include.mk

all:    $(CLASS_DIR)/DisplayFeatureEvent.class \
	$(CLASS_DIR)/DisplayFeatureEventListener.class \
	$(CLASS_DIR)/DisplaySignalValueEvent.class \
	$(CLASS_DIR)/DisplaySignalValueEventListener.class \
	$(CLASS_DIR)/FileNavigateEvent.class \
	$(CLASS_DIR)/FileNavigateEventListener.class \
	$(CLASS_DIR)/SearchEvent.class \
	$(CLASS_DIR)/SearchEventListener.class \
	$(CLASS_DIR)/ZoomEvent.class \
	$(CLASS_DIR)/ZoomEventListener.class
